name: Version increment

on:
  push:
    branches:
      - development
jobs:

  UpdateVersionFile:
    name: Create pull request
    runs-on: ubuntu-latest
    if: "contains(github.event.head_commit.message, '[set version]')"
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Read Version Number
      id: version_number
      uses: juliangruber/read-file-action@v1
      with:
        path: ./VERSION
    
    - name: Check if the commit message contains semantic version
      run: echo ${{ steps.version_number.outputs.content }}
      if: ${{ steps.version_number.outputs.content == '' }}
        echo "Failed to read version"
        exit 1

    - name: Create poll request
      uses: devops-infra/action-pull-request@v0.4.2
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        source_branch: development
        target_branch: main
        title: "Release ${{steps.version_number.outputs.content}}"
        body: "**Automated pull request**"
